<?php
require_once __DIR__ . '/functions.php'; require_login();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $titulo = trim($_POST['titulo'] ?? ''); $contenido = trim($_POST['contenido'] ?? ''); $credit=trim((string)($_POST['image_credit']??''));
    if ($titulo === '' || $contenido === '') { flash('Título y contenido son obligatorios.', 'error'); }
    else { try { if(mb_strlen($credit)>200)throw new RuntimeException('El crédito no puede superar 200 caracteres.');$creditUrl=optional_http_url((string)($_POST['image_credit_url']??''));$contenido = sanitize_html($contenido); if (trim(strip_tags($contenido)) === '') throw new RuntimeException('El contenido no puede estar vacío.'); $imagen = upload_image($_FILES['imagen'] ?? []); $slug = unique_post_slug($titulo); $stmt = db()->prepare('INSERT INTO posts (titulo,slug,contenido,imagen,image_credit,image_credit_url,author_id,author_name) VALUES (?,?,?,?,?,?,?,?)'); $stmt->execute([$titulo,$slug,$contenido,$imagen,$credit?:null,$creditUrl,current_user_id(),current_author_name()]); flash('Artículo publicado.'); redirect(post_url(['slug' => $slug])); } catch (RuntimeException $e) { flash($e->getMessage(), 'error'); } }
}
render_header('Nueva publicación', ['robots' => 'noindex,nofollow']);
?><div class="panel"><h1>Nueva publicación</h1><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><label>Título<input name="titulo" maxlength="200" required></label><label>Imagen de portada<input type="file" name="imagen" accept="image/png,image/jpeg,image/gif,image/webp"></label><div class="settings-grid"><label>Crédito de imagen<input name="image_credit" maxlength="200" value="<?=e($_POST['image_credit']??'')?>" placeholder="Nombre del autor o fuente"></label><label>Enlace del crédito<input type="url" name="image_credit_url" maxlength="500" value="<?=e($_POST['image_credit_url']??'')?>" placeholder="https://..."></label></div><?php render_editor($_POST['contenido'] ?? ''); ?><button class="button">Publicar</button></form></div><?php render_footer(); ?>
