<?php
require_once __DIR__.'/functions.php'; require_once __DIR__.'/mail.php'; $member=require_member(false);
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'save');try{if($action==='resend'){send_verification_email($member);flash('Te enviamos un enlace nuevo.');redirect('/profile.php');}$name=trim((string)($_POST['display_name']??''));$bio=trim((string)($_POST['bio']??''));$public=isset($_POST['profile_public'])?1:0;if(mb_strlen($name)<2||mb_strlen($bio)>500)throw new RuntimeException('Revisa el nombre y la biografía.');$avatar=upload_avatar($_FILES['avatar']??[]);$pdo=db();$pdo->beginTransaction();$sql='UPDATE members SET display_name=?,bio=?,profile_public=?'.($avatar?',avatar=?':'').' WHERE id=?';$args=[$name,$bio,$public];if($avatar)$args[]=$avatar;$args[]=$member['id'];$pdo->prepare($sql)->execute($args);$pdo->prepare('UPDATE posts SET author_name=? WHERE member_author_id=?')->execute([$name,$member['id']]);$pdo->prepare('UPDATE comments SET nombre=? WHERE member_id=?')->execute([$name,$member['id']]);$pdo->commit();if($avatar)delete_image($member['avatar']??null);flash('Perfil actualizado.');redirect('/profile.php');}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();flash($e->getMessage(),'error');}}
render_header('Mi perfil',['robots'=>'noindex,nofollow']);?>
<section class="panel narrow">
<?php if(empty($member['email_verified_at'])):?><div class="verification-box"><strong>Correo pendiente de verificación</strong><form method="post"><input type="hidden" name="csrf_token" value="<?=csrf_token()?>"><input type="hidden" name="action" value="resend"><button class="button">Reenviar enlace</button></form></div><?php endif;?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=csrf_token()?>">
<div class="profile-head"><div class="profile-photo"><div class="avatar-preview" data-avatar-preview><?php if($member['avatar']):?><img class="avatar avatar-lg" src="/uploads/<?=e($member['avatar'])?>" alt="Avatar de <?=e($member['display_name'])?>"><?php else:?><span class="avatar avatar-lg avatar-fallback"><?=e(mb_strtoupper(mb_substr($member['display_name'],0,1)))?></span><?php endif;?></div><label class="avatar-picker"><input type="file" name="avatar" accept="image/png,image/jpeg,image/gif,image/webp" data-avatar-input><span>Elegir imagen</span></label><small data-avatar-status>Máximo 2 MB</small></div><div class="profile-title"><h1>Mi perfil</h1><p class="muted"><?=e($member['email'])?></p><?php if(!empty($member['email_verified_at'])):?><p class="verified">✓ Correo verificado</p><?php endif;?></div></div>
<label>Nombre visible<input name="display_name" maxlength="80" value="<?=e($member['display_name'])?>" required></label><label>Biografía<textarea name="bio" maxlength="500" rows="4"><?=e($member['bio'])?></textarea></label><label class="privacy-toggle"><span><strong>Perfil público</strong><small>Cualquiera podrá ver tu perfil y publicaciones recientes.</small></span><input type="checkbox" name="profile_public" value="1" <?=$member['profile_public']?'checked':''?>><i aria-hidden="true"></i></label><?php if($member['profile_public']):?><p><a class="text-link" href="<?=e(public_profile_url($member))?>">Ver mi perfil público</a></p><?php endif;?><button class="button">Guardar perfil</button></form></section><script src="/assets/avatar-preview.js?v=<?=e((string)(@filemtime(__DIR__.'/assets/avatar-preview.js')?:'1'))?>" defer></script><?php render_footer();
